### ISSUE TITLE
Please add the "Context Actions" command (JetBrains)

### ISSUE THREAD

**Issue by AzimMuradov** [KrazyManJ/obsidian-keyshots#10]
From https://www.jetbrains.com/guide/java/tips/context-actions/
> ⌥⏎ (macOS) / Alt+Enter (Windows/Linux)

P.S.

Really love the plugin, huge thanks!

**Comment by KrazyManJ** [comment]
Hello @AzimMuradov, thank you for your feature request.

This is already possible with native vanilla obsidian via binding <kbd>Alt</kbd> + <kbd>Enter</kbd> shortcut to `Show context menu under cursor` command in Settings > Hotkeys.

Here is screen of my hotkey setting tab showing how I have it in my Obsidian:

![image](https://github.com/KrazyManJ/obsidian-keyshots/assets/79614430/aea0b25e-bee6-4b76-aabb-103a26975136)

That is why I am closing this issue post as not planned, because it is possible in native obsidian via few clicks.

Thank you for using Keyshots ❤️, if you have any other idea of improvement, you are welcome to share it via another issue post.

**Comment by AzimMuradov** [comment]
Thanks!
