### ISSUE TITLE
[Bug] Better Callout Selector sometimes shows Abstract shifted right

### ISSUE THREAD

**Issue by MaxMoldmann** [KrazyManJ/obsidian-keyshots#6]
Often but not always the Better Callout Selector looks like this when opened: the Abstract callout appears shifted to the right
![Abstract-Callout-Shifted](https://github.com/KrazyManJ/obsidian-keyshots/assets/125078514/787b782e-34e4-4b84-bd92-e5efac706caf)
As soon as you type 'A' in the filter it is displayed correctly.

**Comment by KrazyManJ** [comment]
Hello @MaxMoldmann , thank you for another issue post.

Unfortunately this is not issue of Keyshots, but somehow issue of electron (web rendering in an app). While I was trying to check it's render place via developer tools, that abstract callout goes back to it's place. The same is for case when you scroll down, or while you are not focusing input element in modal.

Also I've no idea how to solve this, because in developer tools it's on its place, as it should be, it just appears different. I've tried to solve it months ago but I've been unsuccessful. As you can see I've posted photos of showing item in place in developer tools, but you can see it's not rendered there.

![image](https://github.com/KrazyManJ/obsidian-keyshots/assets/79614430/46898e1b-e2f8-4f5d-9f58-ec6413a40147)

![image](https://github.com/KrazyManJ/obsidian-keyshots/assets/79614430/11cccad7-7008-45b1-b864-5dda8d8cfeb1)

I am sorry but I've done everything what would fix it, unfortunately, I can do nothing about that, because It's not mistake on side of Keyshots, and that's why I am closing this issue, I apologize I could not fix your bug.

Have a great day and again, thank you for trying to make Keyshots a better plugin.

**Comment by MaxMoldmann** [comment]
Thank You for the explanation and your efforts to address this all while not caused by Keyshots (probably my most used Plugin)!
